"""add device category and description

Revision ID: 02aeec8e4304
Revises: 6d47efe6a329
Create Date: 2026-09-13 00:44:10.135367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '02aeec8e4304'
down_revision: Union[str, None] = '6d47efe6a329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('category', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'description')
    op.drop_column('devices', 'category')
    # ### end Alembic commands ###
