"""add device model number and firmware version

Revision ID: 9496b0fe4fea
Revises: d8157de4f87d
Create Date: 2026-09-14 15:16:47.631069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9496b0fe4fea'
down_revision: Union[str, None] = 'd8157de4f87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('model_number', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('firmware_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'firmware_version')
    op.drop_column('devices', 'model_number')
    # ### end Alembic commands ###
