"""add products and device product_id

Revision ID: b8c7b96dd595
Revises: 9496b0fe4fea
Create Date: 2026-09-15 11:18:19.655505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b8c7b96dd595'
down_revision: Union[str, None] = '9496b0fe4fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('data_points', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_org_id'), 'products', ['org_id'], unique=False)
    op.add_column('devices', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_devices_product_id'), 'devices', ['product_id'], unique=False)
    op.create_foreign_key('fk_devices_product_id_products', 'devices', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_devices_product_id_products', 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_product_id'), table_name='devices')
    op.drop_column('devices', 'product_id')
    op.drop_index(op.f('ix_products_org_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
