"""add telemetry readings table

Revision ID: d8157de4f87d
Revises: 02aeec8e4304
Create Date: 2026-09-13 16:41:10.779732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd8157de4f87d'
down_revision: Union[str, None] = '02aeec8e4304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_readings_device_id'), 'telemetry_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_readings_org_id'), 'telemetry_readings', ['org_id'], unique=False)
    op.create_index(op.f('ix_telemetry_readings_recorded_at'), 'telemetry_readings', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_readings_recorded_at'), table_name='telemetry_readings')
    op.drop_index(op.f('ix_telemetry_readings_org_id'), table_name='telemetry_readings')
    op.drop_index(op.f('ix_telemetry_readings_device_id'), table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    # ### end Alembic commands ###
